services:
  - type: web
    name: questionaura-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_AUTH0_DOMAIN
        sync: false
      - key: VITE_AUTH0_CLIENT_ID
        sync: false
      - key: VITE_AUTH0_AUDIENCE
        sync: false
